services:
  mysql:
    image: mysql
    env_file:
      - .env
    # container_name: mysql_db
    # restart: always
    # environment:
    #   MYSQL_DATABASE: 'DBFirstLeap'
    #   MYSQL_USER: 'arianna'
    #   MYSQL_PASSWORD: 'arianna'
    #   MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'

  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mysql
  #   ports:
  #     - '3307:3306'
  # volumes:
  #   - .C:/Users/arian/OneDrive/Ambiente de Trabalho/ipca/PDS
