version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3307
      DATABASE_USER: root_docker
      DATABASE_PASSWORD: root_docker
      DATABASE_NAME: firstleap

  mysql:
    image: mysql
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root_docker
      MYSQL_DATABASE: firstleap_docker
      MYSQL_USER: root_docker
      MYSQL_PASSWORD: root_docker
      MYSQL_TCP_PORT: 3307
